version: '3'

services:

    apache1:
      build: ./Apache
      container_name: apache1
      hostname: apache1
      tty: true
      volumes:
        - ./Apache/site:/var/www/html/

    apache2:
      build: ./Apache
      container_name: apache2
      hostname: apache2
      tty: true
      volumes:
        - ./Apache/site:/var/www/html/

    cache1:
      build: ./Cache/cache1
      # for testing purposes
      ports:
        - "8081:80"
      depends_on:
        - apache1
      hostname: cache1
      container_name: cache1

    cache2:
      build: ./Cache/cache2
      # for testing purposes
      ports:
        - "8082:80"
      depends_on:
        - apache2
      hostname: cache2
      container_name: cache2

    balancer:
      build: ./Balancer
      depends_on:
        - cache1
        - cache2
      ports:
        - "8080:80"
      hostname: balancer
      container_name: balancer

