version: '3'

services:

    apache1:
      build: ./Apache
      container_name: apache1
      hostname: apache1
      volumes:
        - ./Apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

    apache2:
      build: ./Apache
      container_name: apache2
      hostname: apache2
      volumes:
        - ./Apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

    cache1:
      build: ./Cache/cache1
      # for testing purposes
      ports:
        - "8081:80"
      depends_on:
        - apache1
      links:
        - apache1
      hostname: cache1
      container_name: cache1
      volumes:
        - ./Cache/cache1/nginx.conf:/etc/nginx/nginx.conf

    cache2:
      build: ./Cache/cache2
      # for testing purposes
      ports:
        - "8082:80"
      depends_on:
        - apache2
      links:
        - apache2
      hostname: cache2
      container_name: cache2
      volumes:
        - ./Cache/cache2/nginx.conf:/etc/nginx/nginx.conf

    balancer:
      build: ./Balancer
      depends_on:
        - cache1
        - cache2
      ports:
        - "8080:80"
      links:
        - cache1
        - cache2
      hostname: balancer

